### ISSUE TITLE
question about peak.scalability function

### ISSUE THREAD

**Issue by gut0leao** [smoeding/usl#6]
The peak.scalability function for calculating a hypothetical model only accepts variation of the parameters for alpha and beta. Wouldn't it be interesting to include the gamma value? After all, the first measure can be quite reliable and is not under the influence of restraint and coherence.

**Comment by smoeding** [comment]
Until the recent release of version 2.0.0 the package implemented the two parameter version of the USL model. This model only knew the two parameters alpha and beta and therefore the function only had these parameters.

When I updated the package I thought about adding the new gamma parameter to this function. My motivation for the function was to provide a way to predict system behaviour when the contention or cohrerency delay effects were improved. I did not have the prediction of a faster system (more throughput in the single user case) with otherwise unchanged alpha & beta in mind. Therefore I didn't see a real use case.

I can see your point although I believe that using this to "fix" the throughput for the single user case would probably not change the results significantly. All measurements are unreliable in a way.

But, since the change is really not that big, I'm thinking about adding your proposal soon.

**Comment by smoeding** [comment]
Since you specifically reference the `peak.scalability` function: the parameter gamma is not used for this function. The function calculates the point where the peak scalability is reached. In a plot that is the point on the x-axis where the plot reaches its maximum. This depends only on the coefficients alpha & beta. Change gamma would only shift the plot up or down but would not change the point of peak scalability.

On the other hand the parameter would make sense for the `scalability` function that can be used to calculate the specific value at the point where peak scalability is reached. This value would change given a different gamma.

**Comment by gut0leao** [comment]
Thanks for reply, @smoeding.
